version: '3.4'

services:
    vernemq:
        image: vernemq/vernemq
        container_name: vernemq
        environment:
            - DOCKER_VERNEMQ_ALLOW_REGISTER_DURING_NETSPLIT=on
            - DOCKER_VERNEMQ_ALLOW_PUBLISH_DURING_NETSPLIT=on
            - DOCKER_VERNEMQ_ALLOW_SUBSCRIBE_DURING_NETSPLIT=on
            - DOCKER_VERNEMQ_ALLOW_UNSUBSCRIBE_DURING_NETSPLIT=on
            - DOCKER_VERNEMQ_ACCEPT_EULA=yes
            - DOCKER_VERNEMQ_LISTENER__SSL__CAFILE=/etc/certs/ca.crt
            - DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE=/etc/certs/client.crt
            - DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE=/etc/certs/client.key
            - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
            - DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS=5
            - DOCKER_VERNEMQ_LISTENER__SSL__ALLOWED_PROTOCOL_VERSIONS=5
            - DOCKER_VERNEMQ_LISTENER__SSL__REQUIRE_CERTIFICATE=off
            - DOCKER_VERNEMQ_LISTENER__SSL__DEFAULT=0.0.0.0:8883
            - DOCKER_VERNEMQ_USER_ADMIN=pass
        ports:
            - "8883:8883"
            - "1883:1883"
        volumes:
            - ./certs/:/etc/certs